# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huddleupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_firstname', models.CharField(max_length=200)),
                ('contact_lastname', models.CharField(max_length=100)),
                ('contact_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='contact',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
